// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone'], function() {
    var SpeechBubbleView;
    return SpeechBubbleView = (function(_super) {

      __extends(SpeechBubbleView, _super);

      function SpeechBubbleView() {
        return SpeechBubbleView.__super__.constructor.apply(this, arguments);
      }

      SpeechBubbleView.prototype.initialize = function() {
        return this.state = 0;
      };

      SpeechBubbleView.prototype.events = {
        "mouseover": "mouseOver",
        "mouseout": "mouseOut",
        "click": "toggle"
      };

      SpeechBubbleView.prototype.toggle = function() {
        if (this.state === 0) {
          this.state = 1;
          return this.turnOn();
        } else {
          this.turnOff();
          return this.state = 0;
        }
      };

      SpeechBubbleView.prototype.mouseOver = function() {
        return $(this.el).removeClass('hover').addClass('hover');
      };

      SpeechBubbleView.prototype.mouseOut = function() {
        return $(this.el).removeClass('hover');
      };

      SpeechBubbleView.prototype.turnOn = function() {
        $(this.el).removeClass('hover');
        $(this.el).removeClass('off').addClass('on');
        return this.trigger('on');
      };

      SpeechBubbleView.prototype.turnOff = function() {
        $(this.el).removeClass('hover');
        $(this.el).removeClass('on').addClass('off');
        return this.trigger('off');
      };

      return SpeechBubbleView;

    })(Backbone.View);
  });

}).call(this);
