// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone'], function() {
    var SwitchView;
    return SwitchView = (function(_super) {

      __extends(SwitchView, _super);

      function SwitchView() {
        return SwitchView.__super__.constructor.apply(this, arguments);
      }

      SwitchView.prototype.initialize = function() {
        return this.state = 0;
      };

      SwitchView.prototype.events = {
        "click": "toggle"
      };

      SwitchView.prototype.toggle = function() {
        if (this.state === 0) {
          this.state = 1;
          return this.turnOn();
        } else {
          this.turnOff();
          return this.state = 0;
        }
      };

      SwitchView.prototype.turnOn = function() {
        this.trigger('on');
        return $(this.el).removeClass('off').addClass('on');
      };

      SwitchView.prototype.turnOff = function() {
        this.trigger('off');
        return $(this.el).removeClass('on').addClass('off');
      };

      return SwitchView;

    })(Backbone.View);
  });

}).call(this);
